#!/bin/bash
# This file is part of LINPOL, Copyright 2013-2016 Michael F. Herbst
# (info@michael-herbst.com)
#
# LINPOL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This script is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# A copy of the GNU General Public License can be found 
# in the file "LICENCE". If this file is not present in
# this package, see <http://www.gnu.org/licenses/>.
#

. linpol_scripts_common.sh

if echo $@ | grep -w  "\-h" > /dev/null; then
	#we just print help!
	$LINPOL/linpolexe -h
	exit 0
fi

if echo $@ | grep -w  "\-hall" > /dev/null; then
	#we just print help!
	$LINPOL/linpolexe -hall
	exit 0
fi

#Enter Scratch dir
goto_scratch

$LINPOL/linpolexe "$@"
RET=$?

leave_scratch

exit $RET
